version: '3.3'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        PIP_INSTALL: -r requirements-dev.txt
    volumes:
      - type: bind
        source: ..
        target: /opt/osmose-backend
      - type: bind
        source: ../osmose_config_password-example.py
        target: /opt/osmose-backend/osmose_config_password.py
    command: bash
    environment:
      - DB_HOST=postgis
      - DB_BASE_TEST=osmose
