version: '3.3'

services:
  backend:
    volumes:
      - type: bind
        source: ..
        target: /opt/osmose-backend
      - type: bind
        source: ../osmose_config_password-example.py
        target: /opt/osmose-backend/osmose_config_password.py
    environment:
      - DB_HOST=postgis
      - DB_BASE_TEST=osmose
